arrowParens: always
bracketSpacing: true
bracketSameLine: false
endOfLine: auto
jsxSingleQuote: false
jsxBracketSameLine: false
semi: true
singleQuote: false
tabWidth: 2
trailingComma: all
plugins: [ ]
printWidth: 100
